#! /usr/bin/env php


<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('Portal Application Developer Tools', '1.0');

$app->add(new Portal\Tools\BuildCommand);

$app->run();
